name: Use Composite Action
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Standard Python Steps
        uses: ./github/actions
        with:
          PYTHON_VERSION: '3.8'
          RUN_UNIT_TESTS: 'true'
